using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
    public class Task2
    {
        public void EvenFibonacciNumbers()
        {
            //Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
            //By starting with 1 and 2, the first 10 terms will be:
            //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            //By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
            //find the sum of the even-valued terms.

            //create Fibonacci sequence
            long n = long.Parse(Console.ReadLine()); // number of elements we want found
            long firstElement = 1;
            long secondElement = 2;
            long temporary = 0;
            long sum = 0;
            Console.Write(firstElement + " ");
            Console.Write(secondElement + " ");

            for (int i = 2; i < n; i++)
            {
                temporary = secondElement; //8
                secondElement = firstElement + secondElement; //13
                //Console.Write(secondElement + " "); //8
                if (secondElement < 4000000 && secondElement % 2 == 0)
                {
                    sum = sum + secondElement;
                }
                firstElement = temporary; //5
            }

            Console.WriteLine(sum + 2);
        }

    }
}
